version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/test_aws_cd
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 180
      runas: ubuntu
